# verify.yml
---
 - name: run task on JNIFI & JSED
   hosts: all_hosts
   tasks:
    - name: Add the line if it does not exist
      become: yes
      become_user: root
      lineinfile:
          path: /etc/audit/audit.rules
          line: "-a always,exit -F path=/usr/bin/kmod -F perm=x -F auid>=1000 -F auid!=unset -k modules"
          state: present
          backup: yes
    - name: Add the line if it does not exist
      become: yes
      become_user: root
      lineinfile:
          path: /etc/audit/audit.rules
          line: "-a always,exit -F arch=b32 -S execve -C uid!=euid -F euid=0 -k setuid"
          state: present
          backup: yes
    - name: Add the line if it does not exist
      become: yes
      become_user: root
      lineinfile:
          path: /etc/audit/audit.rules
          line: "-a always,exit -F arch=b64 -S execve -C uid!=euid -F euid=0 -k setuid"
          state: present
          backup: yes
    - name: Add the line if it does not exist
      become: yes
      become_user: root
      lineinfile:
          path: /etc/audit/audit.rules
          line: "-a always,exit -F arch=b32 -S execve -C gid!=egid -F egid=0 -k setgid"
          state: present
          backup: yes
    - name: Add the line if it does not exist
      become: yes
      become_user: root
      lineinfile:
          path: /etc/audit/audit.rules
          line: "-a always,exit -F arch=b64 -S execve -C gid!=egid -F egid=0 -k setgid"
          state: present
          backup: yes
    - name: Change file ownership, group and permissions
      become: yes
      become_user: root
      ansible.builtin.file:
       path: /etc/profile.d/tmout.sh
       owner: root
       group: root
       mode: '0744'