 # verify.yml
---
 - name: run task on all hosts
   hosts: all_hosts
   tasks:
    - name: Confirming audisp-remote.conf file
      become_user: root
      become: yes
      shell: cat /etc/audisp/plugins.d/au-remote.conf | grep -v "^#
      register: grep_output

    - name: print output
      debug:
        var: grep_output.stdout_lines