# httpd-conf.yml
---
 - name: run task on all hosts
   hosts: nifi_all
   tasks:
    - name: rm file
      become_user: root
      become: yes
      shell: rm -f /opt/nifi-external-jars/analytics/additional_jars/bundled-dependencies/log4j-1.2.17.jar
    - name: Confirming rm
      become_user: root
      become: yes
      shell: ls -la /opt/nifi-external-jars/analytics/additional_jars/bundled-dependencies/ | grep -i "log4j-1.2.17.jar"
      register: grep_output
    - name: print output
      debug:
        var: grep_output.stdout_lines
    - name: Copy updated chronyd.conf File
      become_user: root
      become: yes
      copy:
        src: /home/chi.oparaoji.adm/log4j*
        dest: "/opt/nifi-external-jars/analytics/additional_jars/bundled-dependencies/"
        owner: nifi
        group: nifi
        mode: "664"
        force: yes