---
 - name: Deploy UI WAR
   hosts: uat_tomcat_hosts
   tasks:
    - name: Copy ROOT.war
      become_user: root
      become: yes
      copy:
        src: /home/rpms/ROOT.war
        dest: /var/lib/csca/webapps/ROOT.war
        owner: tomcat
        group: tomcat
        mode: "644"
        force: yes
    - name: create symlink for the ROOT.war
      become: yes
      file:
        src: /var/lib/csca/webapps/ROOT.war
        dest: /usr/share/tomcat/webapps/ROOT.war
        state: link
        owner: tomcat
        group: tomcat
        force: yes
    - name: stop tomcat
      become_user: root
      become: yes
      shell: systemctl stop tomcat
    - name: start tomcat
      become_user: root
      become: yes
      shell: systemctl start tomcat