---
 - name: Install and configure idm client
   hosts: uat_hosts
   tasks:
    - name: Copy sssd File
      become_user: root
      become: yes
      template:
        src: /etc/ansible/templates/sssd.conf.j2
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: "600"
        force: yes
    - name: update authconfig
      become_user: root
      become: yes
      shell: /usr/sbin/authconfig --disableldapauth --disableldap --enablesssdauth --enablemkhomedir --updateall
    - name: stop sssd
      become_user: root
      become: yes
      shell: systemctl stop sssd
    - name: clear sssd cache
      become_user: root
      become: yes
      shell: /usr/sbin/sss_cache -E
    - name: start sssd
      become_user: root
      become: yes
      shell: systemctl start sssd