# verify.yml
---
 - name: add new lines to system-auth and password-auth on memcached hosts
   hosts: memcached_hosts
   tasks:
    - name: make backup of systemc-auth 
      become_user: root
      become: yes
      shell: cp -p /etc/pam.d/system-auth /etc/pam.d/system-auth-backup-20220804
    - name: make backup of password-auth 
      become_user: root
      become: yes
      shell: cp -p /etc/pam.d/password-auth /etc/pam.d/password-auth-backup-20220804
    - name: make sure backups have been made 
      become_user: root
      become: yes
      shell: ls -lart /etc/pam.d
      register: grep_output
    - name: print output
      debug:
        var: grep_output.stdout_lines
    - name: Copy new system-auth File
      become_user: root
      become: yes
      copy:
        src: /etc/ansible/templates/system-auth
        dest: "/etc/pam.d/system-auth"
        owner: root
        group: root
        mode: "644"
        force: yes
    - name: Copy new password-auth File
      become_user: root
      become: yes
      copy:
        src: /etc/ansible/templates/password-auth
        dest: "/etc/pam.d/password-auth"
        owner: root
        group: root
        mode: "644"
        force: yes
    - name: make sure files have been updated 
      become_user: root
      become: yes
      shell: ls -lart /etc/pam.d
      register: grep_output2
    - name: print output
      debug:
        var: grep_output2.stdout_lines