# logrotate_fix.yml
---
 - name: run task on all hosts
   hosts: all_hosts
   tasks:
    - name: Confirming logrotate.conf file
      become_user: root
      become: yes
      shell: grep min /etc/logrotate.conf
      register: grep_output

    - name: print output
      debug:
        var: grep_output.stdout_lines

    - name: Copy updated logrotate.conf File
      become_user: root
      become: yes
      copy:
        src: /etc/logrotate.conf
        dest: "/etc/logrotate.conf"
        owner: root
        group: root
        mode: "644"
        force: yes

    - name: Confirming logrotate.conf file
      become_user: root
      become: yes
      shell: grep max /etc/logrotate.conf
      register: grep_output

    - name: print output
      debug:
        var: grep_output.stdout_lines