# verify.yml
---
 - name: run task on all hosts
   hosts: tomcat_hosts
   tasks:
    - name: Copy server.xml File
      become_user: root
      become: yes
      copy:
        src: /home/chi.oparaoji.adm/server.xml-JCITS-1262
        dest: "/etc/tomcat/server.xml"
        owner: root
        group: root
        mode: "644"
        force: yes
    - name: Confirming server.xml file
      become_user: root
      become: yes
      shell: cat /home/chi.oparaoji.adm/server.xml-JCITS-1262 | grep "autoDeploy="
      register: grep_output

    - name: print output
      debug:
        var: grep_output.stdout_lines