 # verify.yml
---
 - name: run task on all hosts
   hosts: all_hosts
   tasks:
    - name: Confirming postlogin file
      become_user: root
      become: yes
      shell: grep pam_lastlog /etc/pam.d/postlogin
      register: grep_output

    - name: print output
      debug:
        var: grep_output.stdout_lines

    - name: Copy updated postlogin File
      become_user: root
      become: yes
      copy:
        src: /etc/pam.d/postlogin
        dest: "/etc/pam.d/postlogin"
        owner: root
        group: root
        mode: "644"
        force: yes

    - name: Confirming updated postlogin file
      become_user: root
      become: yes
      shell: grep pam_lastlog /etc/pam.d/postlogin
      register: grep_output
     
    - name: print output
      debug:
        var: grep_output.stdout_lines      